# Generated by Django 2.0.2 on 2019-01-20 16:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
