# Generated by Django 2.0.2 on 2019-03-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('extension', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('mimeType', models.CharField(max_length=250)),
                ('webLink', models.CharField(max_length=1024)),
                ('filePath', models.CharField(max_length=250)),
                ('size', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
