# Generated by Django 2.0.2 on 2019-01-18 10:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('longitude', models.DecimalField(decimal_places=12, max_digits=20)),
                ('latitude', models.DecimalField(decimal_places=12, max_digits=20)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Report')),
            ],
        ),
    ]
