# Generated by Django 2.0.2 on 2019-01-19 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('sub_domian', models.CharField(max_length=30)),
                ('has_public_module', models.BooleanField(default=True)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('brand_primary_color', models.CharField(max_length=10)),
                ('brand_secondry_color', models.CharField(max_length=10)),
                ('website', models.URLField(max_length=10)),
                ('bio', models.CharField(max_length=1000)),
                ('legal_name', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('point_of_contact', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='profiles.Profile')),
            ],
        ),
    ]
