# Generated by Django 2.0.2 on 2019-01-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('sub_domian', models.CharField(max_length=30)),
                ('has_public_module', models.BooleanField(default=True)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('brand_primary_color', models.CharField(max_length=10)),
                ('brand_secondry_color', models.CharField(max_length=10)),
                ('website', models.URLField(max_length=10)),
                ('bio', models.CharField(max_length=1000)),
                ('legal_name', models.CharField(max_length=1000)),
            ],
        ),
    ]
