# Generated by Django 2.0.2 on 2019-01-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='website',
            field=models.URLField(max_length=2000),
        ),
    ]
