# Generated by Django 2.0.2 on 2019-01-18 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='point_of_contact',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='profiles.Profile'),
            preserve_default=False,
        ),
    ]
