# Generated by Django 2.0.2 on 2019-01-18 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='projects.ProjectType'),
            preserve_default=False,
        ),
    ]
